name: GitHub Clone Count Update Everyday
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Traffic to Badge
        uses: yi-Xu-0100/traffic-to-badge@v1.6.0
        with:
          my_token: ${{ secrets.SECRET_TOKEN }}
