# Refer to https://wiki.hypr.land/Configuring/Variables/
# https://wiki.hypr.land/Configuring/Variables/#general

### General ###
general {
  gaps_in = 6
  gaps_out = 20, 20, 20, 20  # top, right, bottom, left

  border_size = 2
  col.active_border = 0xff7287fd 0xff89b4fa 45deg
  col.inactive_border = 0xff313244

  resize_on_border = true
  extend_border_grab_area = 15
  hover_icon_on_border = true

  layout = dwindle
  allow_tearing = false

  snap {
    enabled = true
    window_gap = 10
    monitor_gap = 10
  }
}

### Decoration ####
decoration {
  rounding = 18
  rounding_power = 2.5 
  # Transparansi
  active_opacity = 1.0
  inactive_opacity = 0.9
  fullscreen_opacity = 1.0
  # Dimming
  dim_inactive = true
  dim_strength = 0.2
  dim_modal = true
  dim_special = 0.2
  dim_around = 0.4
  # Border Behavior
  border_part_of_window = true

  #shadow {
  #  enabled = true
  #  range = 10
  #  render_power = 3
  #  color = 0x44000000
  #}
  blur {
    enabled = true
    size = 5
    passes = 2

    new_optimizations = true
    xray = true #true

    ignore_opacity = true

    vibrancy = 0.2
    #contrast = 1.0
    #brightness = 1.0

    popups = true 
  }

}

### https://wiki.hypr.land/Configuring/Animations/
### Animations ###
animations {
  enabled = true
  workspace_wraparound = false

  # --- BEZIER ---
  bezier = refined,   0.16, 1,    0.3,  1
  bezier = swift,     0.76, 0,    0.24, 1
  bezier = momentum,  0.25, 0.46, 0.45, 0.94
  bezier = whisper,   0.40, 0,    0.60, 1
  bezier = overture,  0.34, 1.08, 0.64, 1

  # --- GLOBAL ---
  animation = global, 1, 4, refined

  # --- WINDOWS ---
  animation = windows,     1, 3, refined,  slide
  animation = windowsIn,   1, 4, overture, popin 10%
  animation = windowsOut,  1, 2, swift,    popin 90%
  animation = windowsMove, 1, 4, refined

  # --- FADE ---
  animation = fade,    1, 4, whisper
  animation = fadeIn,  1, 4, refined
  animation = fadeOut, 1, 2, swift

  # --- LAYERS ---
  animation = layers,    1, 3, refined, slide
  animation = layersIn,  1, 4, refined, slide
  animation = layersOut, 1, 2, swift,   slide

  # --- WORKSPACES ---
  animation = workspaces,       1, 4, momentum, slidefade 15%
  animation = specialWorkspace, 1, 4, refined,  slidevert

  # --- BORDER ---
  animation = border,     1, 6, whisper
  animation = zoomFactor, 1, 4, refined
}

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = true
    force_split = 2
    special_scale_factor = 0.8
    split_width_multiplier = 1.2
    use_active_for_splits = true
}
# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  disable_splash_rendering = true
  animate_manual_resizes = true
  initial_workspace_tracking = 1
  vrr = 1
}

