# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

#### --- Windowrules --- ###
xwayland {
  force_zero_scaling = true
}

# Super shift M & super M
windowrule {
  name = magic-floating
  match:workspace = s[true]
  float = true
}
workspace = s[true], gapsout:200, gapsin:10, rounding:true, border:true, shadow:true

windowrule {
  name = suppress-maximize-events
  match:class = .*

  suppress_event = maximize
}

windowrule {
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false

  no_focus = true
}

# Hyprland-run windowrule
windowrule {
  name = move-hyprland-run
  match:class = hyprland-run
  move = 20 monitor_h-120
  float = yes
}

# --- Fix Screen Sharing (Xwayland Video Bridge) ---
windowrule {
  name = xwayland-video-bridge-fixes
  match:class = xwaylandvideobridge

  # Effects
  opacity = 0.0
  no_anim = on
  no_focus = true
  no_initial_focus = true
  max_size = 1 1
  no_blur = true
}

windowrule {
  name = google-meet-sharing
  match:title = ^(Sharing).*$
  match:class = ^(google-chrome|firefox|Brave-browser)$

  float = true
}

windowrule {
  name = zoom-fixes
  match:class = ^(zoom)$

  float = true
}

windowrule {
  name = zoom-sharing-status
  match:class = ^(zoom)$
  match:title = ^(as_toolbar).*$

  no_anim = on
  no_blur = true
}

windowrule {
  name = obs-fixes
  match:class = ^(com.obsproject.Studio)$

  float = true
}

windowrule {
  name = obs-preview
  match:class = ^(com.obsproject.Studio|obs)$
  match:title = ^(Preview).*$

  no_blur = true
}

windowrule {
  name = file-manager
  match:class = ^(thunar)$
  float = true
  size = 713 502
  move = 704 65
}

windowrule {
  name = pavucontrol
  match:class = ^(org.pulseaudio.pavucontrol)$
  float = true
  size = 700 450
  move = 370 65
}

windowrule {
  name = blueman
  match:class = ^(blueman-manager)$
  float = true
  size = 578 310
  move = 840 65
}


### --- Firs Login ---###
windowrule {
  name = terminal-bawah
  match:class = kitty-bawah
  float = true
  size = 893 540
  move = 50 332
  no_dim = on
  border_size = 4
  force_rgbx = on
  no_blur = on
  opacity = 1.0 override 1.0 override 1.0 override
}

windowrule {
  name = nvim-kanan
  match:class = kitty-nvim
  float = true
  size = 716 757
  move = 679 67
  no_dim = on
  border_size = 4
}

windowrule {
  name = kitty-jam
  match:class = kitty-jam
  float = true
  size = 578 280
  move = 49 64
  no_dim = on
  border_size = 4
}
windowrule = match:float true, size 964 558, center on
windowrule = no_blur on, match:class firefox

### --- Layerrules --- ###
layerrule = no_anim on, match:namespace logout_dialog
layerrule = animation fade, match:namespace rofi
layerrule = no_anim on, match:namespace hyprpicker
layerrule = animation fade, match:namespace hyprpaper
